### ISSUE TITLE
Error with Quora plugin

### ISSUE THREAD

**Issue by teepee-git** [eloquence/freeyourstuff.cc#107]
TypeError: moment(...).day(...).format is not a function
    at extractAnswer (file:///home/thom/.config/google-chrome/Default/Extensions/hlkhpekhgcaigleojiocoeockhcaglia/0.4.8_0/src/plugins/quora/index.js:279:47)
    at extractAndHideVisibleAnswers (file:///home/thom/.config/google-chrome/Default/Extensions/hlkhpekhgcaigleojiocoeockhcaglia/0.4.8_0/src/plugins/quora/index.js:186:37)
    at async retrieveAnswers (file:///home/thom/.config/google-chrome/Default/Extensions/hlkhpekhgcaigleojiocoeockhcaglia/0.4.8_0/src/plugins/quora/index.js:90:17)

**Comment by eloquence** [comment]
Thanks for the report! I was not able to reproduce it, but I did notice that date extraction broke, which may be related. I just pushed a version update, could you try again after verifying that you are running 0.4.9 by visiting chrome://extensions ?

If you still get the bug, could you point me to your public Quora profile URL?

**Comment by teepee-git** [comment]
Hi Erik,

With the previous version, I did try many times and tried removing and re-installing.
I updated to 0.4.9 and that seems to have fixed it. No problems so far :)
