### ISSUE TITLE
Error with Goodreads plugin on Chrome/MacOS

### ISSUE THREAD

**Issue by mayel** [eloquence/freeyourstuff.cc#86]
Error: Export never completed.
    at Object.getConnectionError (file:///Users/me/Library/Application%20Support/Google/Chrome/Default/Extensions/hlkhpekhgcaigleojiocoeockhcaglia/0.4.0_0/src/plugin.js:215:21)
    at Object.$.ajax.done.fail.event (file:///Users/me/Library/Application%20Support/Google/Chrome/Default/Extensions/hlkhpekhgcaigleojiocoeockhcaglia/0.4.0_0/src/plugins/goodreads/index.js:190:29)
    at j (file:///Users/me/Library/Application%20Support/Google/Chrome/Default/Extensions/hlkhpekhgcaigleojiocoeockhcaglia/0.4.0_0/src/lib/js/jquery-2.1.4.min.js:2:26925)
    at Object.fireWith [as rejectWith] (file:///Users/me/Library/Application%20Support/Google/Chrome/Default/Extensions/hlkhpekhgcaigleojiocoeockhcaglia/0.4.0_0/src/lib/js/jquery-2.1.4.min.js:2:27738)
    at x (file:///Users/me/Library/Application%20Support/Google/Chrome/Default/Extensions/hlkhpekhgcaigleojiocoeockhcaglia/0.4.0_0/src/lib/js/jquery-2.1.4.min.js:4:11278)
    at XMLHttpRequest. (file:///Users/me/Library/Application%20Support/Google/Chrome/Default/Extensions/hlkhpekhgcaigleojiocoeockhcaglia/0.4.0_0/src/lib/js/jquery-2.1.4.min.js:4:14765)Additional details: {
  "statusCode": 404,
  "statusText": "Not Found",
  "url": "https://www.goodreads.com/review_porter/export/4133618/goodreads_export.csv"
}

**Comment by mayel** [comment]
I tested that URL (in the browser where I am authenticated) and it did download a CSV of my booklist.

**Comment by eloquence** [comment]
It's possible that it timed out before freeyourstuff could grab it. :( The timeout is 12.5 seconds, which may be a bit short. Is it reproducible?

**Comment by mayel** [comment]
Yeah I'm getting the same error on Goodreads every time.
IMDB worked OK though.

**Comment by eloquence** [comment]
It's odd but not impossible that it just takes a while longer for you -- on my system, the export completes on average in about half the timeout. I'll set the timeout to 30 seconds in a minor release and will bump this bug once it's pushed out so we can try again to see if that's the issue.

**Comment by eloquence** [comment]
Should be fixed with https://github.com/eloquence/freeyourstuff.cc/commit/837985655992c4feb667b8efc4985a631d89f61a which I just pushed out -- once your chrome://extensions shows 0.4.1 (probably by tomorrow), let's try again to see if that was indeed the issue.

**Comment by mayel** [comment]
That worked, thanks :)
